
export const GET_PARK = 'redux/GET_PARK';
export const GET_PARK_REQUEST = 'redux/GET_PARK_REQUEST';
export const GET_PARK_REQUEST_SUCCESS = 'redux/GET_PARK_REQUEST_SUCCESS';
export const GET_PARK_REQUEST_FAILURE = 'redux/GET_PARK_REQUEST_FAILURE';
export const GET_PARK_REQUEST_END = 'redux/GET_PARK_REQUEST_END';

export const GET_PARK_ID = 'redux/GET_PARK_ID';
export const GET_PARK_ID_REQUEST = 'redux/GET_PARK_ID_REQUEST';
export const GET_PARK_ID_REQUEST_SUCCESS = 'redux/GET_PARK_ID_REQUEST_SUCCESS';
export const GET_PARK_ID_REQUEST_FAILURE = 'redux/GET_PARK_ID_REQUEST_FAILURE';
export const GET_PARK_ID_REQUEST_END = 'redux/GET_PARK_ID_REQUEST_END';

